services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: creditdb
      POSTGRES_USER: credituser
      POSTGRES_PASSWORD: creditpass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: .
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      # Mount the backend folder contents directly into /code so manage.py is /code/manage.py
      - ./backend/:/code/
      - ./customer_data.xlsx:/code/customer_data.xlsx
      - ./loan_data.xlsx:/code/loan_data.xlsx
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SECRET_KEY=DJANGO_SECRET_KEY="key""
      - DJANGO_DEBUG=True
      - POSTGRES_DB=creditdb
      - POSTGRES_USER=credituser
      - POSTGRES_PASSWORD=creditpass
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - DJANGO_SETTINGS_MODULE=backend.settings   # Added this to fix settings module error
    depends_on:
      - db
      - redis

  celery:
    build: .
    command: celery -A backend worker -l info
    volumes:
      - ./backend/:/code/
      - ./customer_data.xlsx:/code/customer_data.xlsx
      - ./loan_data.xlsx:/code/loan_data.xlsx
    environment:
      - DJANGO_SECRET_KEY=DJANGO_SECRET_KEY="key"
      - DJANGO_DEBUG=True
      - POSTGRES_DB=creditdb
      - POSTGRES_USER=credituser
      - POSTGRES_PASSWORD=creditpass
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=django-db
      - DJANGO_SETTINGS_MODULE=backend.settings  # Added here as well
    depends_on:
      - db
      - redis

  redis:
    image: redis:7
    ports:
      - "6379:6379"

volumes:
  postgres_data:
